Update bug-report.md
VishnuSanal/Quotes pull request #64
Opened 2021-11-02 15:54 UTC by shuvashish76

2021-11-02 18:00 UTC, VishnuSanal requested changes
@shuvashish76 Please see the comments

2021-11-02 18:00 UTC, VishnuSanal commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - Device: [e.g. One Plus 8 Pro]
OnePlus!

2021-11-02 18:11 UTC, shuvashish76 commented on .github/ISSUE_TEMPLATE/bug-report.md
> +about: Create a report to help us improve
Everything copied from : https://github.com/MuntashirAkon/AppManager/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

> "Report bugs to help us improve" sounds good to me
Ok👍🏿

2021-11-03 07:22 UTC, VishnuSanal approved these changes

2021-11-03 07:22 UTC, merged